name: modbus_client
description: This is the base Modbus Client package sending requests to a remote device (i.e. Modbus Server) via Serial (ASCII and RTU) or TCP/IP connection.
version: 1.0.0
repository: https://github.com/cabbi/modbus_client

environment:
  sdk: ^2.17.0

dependencies:
  collection: ^1.17.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  modbus_client_tcp:
    path: ../modbus_client_tcp
  modbus_client_serial:
    path: ../modbus_client_serial
